# Site settings
title: "Eduardo Menezes Rocha"
description: "My resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Eduardo Menezes Rocha"
resume_title:                   "Software Engineer"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "eduardomenezesr@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     "Foz do Igua√ßu, Brasil"
display_header_contact_info:    "true"

resume_header_intro: "<p>BSc in Computer Science and currently a postgraduate student in Distributed Software Architecture. My career started at a foreign exchange bank as a software developer and later as a software architect, so I created a special affection for the financial area. Actively seeking new challenges abroad.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           false
resume_section_associations:    false
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/eduardomrocha"
  #resume_twitter_url:           "http://twitter.com/"
  #resume_dribbble_url:          "https://dribbble.com/"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/eduardomrocha"
  # resume_instagram_url:         "insert your Instagram URL here"
  #resume_website_url:           "http://"
  #resume_medium_url:            "https://medium.com/@"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
